import React, {useEffect, useState} from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  Image,
  ActivityIndicator,
  ScrollView,
  Dimensions,
} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useRouter, useLocalSearchParams} from 'expo-router';
import {SparklesIcon} from 'react-native-heroicons/solid';
import {ArrowPathIcon} from 'react-native-heroicons/outline';

const {width, height} = Dimensions.get('window');
const wp = (percentage: number) => (width * percentage) / 100;
const hp = (percentage: number) => (height * percentage) / 100;

interface GeneratedProfile {
  id: string;
  photo_url: string;
  generated_bio: string;
  personality_traits: string[];
  interests: string[];
  conversation_starters: string[];
  ai_provider: string;
}

export default function ProfilePreviewScreen() {
  const router = useRouter();
  const params = useLocalSearchParams();
  const {profileId} = params;

  const [profile, setProfile] = useState<GeneratedProfile | null>(null);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);

  useEffect(() => {
    fetchProfile();
  }, [profileId]);

  const fetchProfile = async () => {
    try {
      setLoading(true);
      const backendUrl = process.env.EXPO_PUBLIC_BACKEND_URL || 'http://localhost:3000';

      const response = await fetch(`${backendUrl}/api/profile/${profileId}`);
      const result = await response.json();

      if (result.success) {
        setProfile(result.profile);
      }
    } catch (error) {
      console.error('Error fetching profile:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleRegenerate = async () => {
    try {
      setRegenerating(true);
      const backendUrl = process.env.EXPO_PUBLIC_BACKEND_URL || 'http://localhost:3000';

      // Switch to a different AI provider
      const newProvider = profile?.ai_provider === 'claude' ? 'openai' : 'claude';

      const response = await fetch(`${backendUrl}/api/profile/regenerate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          userId: profileId,
          photoUrl: profile?.photo_url,
          provider: newProvider,
        }),
      });

      const result = await response.json();

      if (result.success) {
        setProfile(result.profile);
      }
    } catch (error) {
      console.error('Error regenerating profile:', error);
    } finally {
      setRegenerating(false);
    }
  };

  const handleContinue = () => {
    // Navigate to student info form
    router.push('/(onboarding)/student-info');
  };

  if (loading) {
    return (
      <SafeAreaView className="flex-1 bg-white items-center justify-center">
        <ActivityIndicator size="large" color="#F26322" />
        <Text
          className="mt-4 text-gray-600"
          style={{fontFamily: 'SpaceGrotesk-Regular'}}
        >
          AI is creating your profile...
        </Text>
      </SafeAreaView>
    );
  }

  if (!profile) {
    return (
      <SafeAreaView className="flex-1 bg-white items-center justify-center px-6">
        <Text
          className="text-xl text-gray-900"
          style={{fontFamily: 'SpaceGrotesk-SemiBold'}}
        >
          Profile not found
        </Text>
        <TouchableOpacity
          className="mt-4 bg-[#F26322] px-6 py-3 rounded-xl"
          onPress={() => router.back()}
        >
          <Text
            className="text-white font-bold"
            style={{fontFamily: 'SpaceGrotesk-Bold'}}
          >
            Go Back
          </Text>
        </TouchableOpacity>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView className="flex-1 bg-white">
      <ScrollView className="flex-1">
        <View className="px-6 py-4">
          {/* Header */}
          <View className="items-center mb-6">
            <View className="flex-row items-center">
              <SparklesIcon size={24} color="#F26322" />
              <Text
                className="text-2xl font-bold text-gray-900 ml-2"
                style={{fontFamily: 'SpaceGrotesk-Bold'}}
              >
                Your AI Profile
              </Text>
            </View>
            <Text
              className="text-sm text-gray-500 mt-1"
              style={{fontFamily: 'SpaceGrotesk-Regular'}}
            >
              Generated by {profile.ai_provider === 'claude' ? 'Claude AI' : 'OpenAI'}
            </Text>
          </View>

          {/* Photo */}
          <Image
            source={{uri: profile.photo_url}}
            style={{
              width: wp(88),
              height: hp(40),
              borderRadius: 20,
            }}
            resizeMode="cover"
            className="mb-6"
          />

          {/* Bio */}
          <View className="mb-6">
            <Text
              className="text-sm text-gray-500 mb-2 uppercase tracking-wider"
              style={{fontFamily: 'SpaceGrotesk-SemiBold'}}
            >
              Bio
            </Text>
            <Text
              className="text-base text-gray-800 leading-6"
              style={{fontFamily: 'SpaceGrotesk-Regular'}}
            >
              {profile.generated_bio}
            </Text>
          </View>

          {/* Personality Traits */}
          {profile.personality_traits && profile.personality_traits.length > 0 && (
            <View className="mb-6">
              <Text
                className="text-sm text-gray-500 mb-2 uppercase tracking-wider"
                style={{fontFamily: 'SpaceGrotesk-SemiBold'}}
              >
                Personality
              </Text>
              <View className="flex-row flex-wrap">
                {profile.personality_traits.map((trait, index) => (
                  <View
                    key={index}
                    className="bg-[#F26322]/10 px-3 py-2 rounded-full mr-2 mb-2"
                  >
                    <Text
                      className="text-[#F26322]"
                      style={{fontFamily: 'SpaceGrotesk-Medium'}}
                    >
                      {trait}
                    </Text>
                  </View>
                ))}
              </View>
            </View>
          )}

          {/* Interests */}
          {profile.interests && profile.interests.length > 0 && (
            <View className="mb-6">
              <Text
                className="text-sm text-gray-500 mb-2 uppercase tracking-wider"
                style={{fontFamily: 'SpaceGrotesk-SemiBold'}}
              >
                Interests
              </Text>
              <View className="flex-row flex-wrap">
                {profile.interests.map((interest, index) => (
                  <View
                    key={index}
                    className="bg-gray-200 px-3 py-2 rounded-full mr-2 mb-2"
                  >
                    <Text
                      className="text-gray-700"
                      style={{fontFamily: 'SpaceGrotesk-Medium'}}
                    >
                      {interest}
                    </Text>
                  </View>
                ))}
              </View>
            </View>
          )}

          {/* Conversation Starters */}
          {profile.conversation_starters &&
            profile.conversation_starters.length > 0 && (
              <View className="mb-6">
                <Text
                  className="text-sm text-gray-500 mb-2 uppercase tracking-wider"
                  style={{fontFamily: 'SpaceGrotesk-SemiBold'}}
                >
                  Conversation Starters
                </Text>
                {profile.conversation_starters.map((starter, index) => (
                  <View key={index} className="mb-2 flex-row">
                    <Text className="text-[#F26322] mr-2">•</Text>
                    <Text
                      className="flex-1 text-gray-700"
                      style={{fontFamily: 'SpaceGrotesk-Regular'}}
                    >
                      {starter}
                    </Text>
                  </View>
                ))}
              </View>
            )}
        </View>
      </ScrollView>

      {/* Actions */}
      <View className="px-6 pb-6 border-t border-gray-200 pt-4">
        <TouchableOpacity
          className="bg-gray-200 px-6 py-3 rounded-xl flex-row justify-center items-center mb-3"
          onPress={handleRegenerate}
          disabled={regenerating}
        >
          {regenerating ? (
            <ActivityIndicator color="#374151" />
          ) : (
            <>
              <ArrowPathIcon size={20} color="#374151" />
              <Text
                className="text-gray-700 font-semibold ml-2"
                style={{fontFamily: 'SpaceGrotesk-SemiBold'}}
              >
                Regenerate with Different AI
              </Text>
            </>
          )}
        </TouchableOpacity>

        <TouchableOpacity
          className="bg-[#F26322] px-6 py-4 rounded-xl items-center"
          onPress={handleContinue}
        >
          <Text
            className="text-white font-bold text-lg"
            style={{fontFamily: 'SpaceGrotesk-Bold'}}
          >
            Looks Good! Continue →
          </Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}
